name: Trigger auto deployment for cmmc-env

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cmmc-env-AutoDeployTrigger-0a4b6988-1adc-427b-8e69-9dc1eb66e334.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CMMCENV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CMMCENV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CMMCENV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: 
          registryUsername: ${{ secrets.CMMCENV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CMMCENV_REGISTRY_PASSWORD }}
          containerAppName: cmmc-env
          resourceGroup: cmmc-resource
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
            _buildArgumentsValues_


